apiVersion: v1
kind: Namespace
metadata:
  name: app-dashy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dashboard-deployment
  namespace: app-dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dashboard
  template:
    metadata:
      labels:
        app: my-dashboard
    spec:
      containers:
        - name: my-dashboard
          image: lissy93/dashy:2.1.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /app/public/conf.yml
              subPath: conf.yml
      volumes:
        - name: config-volume
          configMap:
            name: my-dashboard-config
---
apiVersion: v1
kind: Service
metadata:
  name: my-dashboard-service
  namespace: app-dashy
spec:
  selector:
    app: my-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy-ingress
  namespace: app-dashy
spec:
  rules:
    - host: dash.travismtg.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-dashboard-service
                port:
                  number: 80
